# Generated by Django 5.2.1 on 2025-05-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lemmy", "0002_upgrade_to_019"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageDetails",
            fields=[
                ("link", models.TextField(primary_key=True, serialize=False)),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("content_type", models.TextField()),
            ],
            options={
                "db_table": "image_details",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="ImageUpload",
        ),
    ]
