# Generated by Django 4.2.13 on 2024-07-17 20:11

from django.db import migrations, models
import django.db.models.deletion
import fediverser.apps.core.models.activitypub


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="core.instance",
                    ),
                ),
            ],
            bases=(models.Model, fediverser.apps.core.models.activitypub.ActorMixin),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="lemmy_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portal_account",
                to="core.person",
            ),
        ),
    ]
