# Generated by Django 4.2.6 on 2023-10-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_redditaccount_marked_as_spammer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="redditcomment",
            name="marked_as_spam",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="redditsubmission",
            name="marked_as_duplicate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="redditsubmission",
            name="marked_as_spam",
            field=models.BooleanField(default=False),
        ),
    ]
