# Generated by Django 4.2.13 on 2024-07-19 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_fediversedinstance_instance_endorsement_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="endorsemententry",
            old_name="endorsemement",
            new_name="endorsement",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="lemmy_account",
        ),
        migrations.AlterField(
            model_name="connectedredditaccount",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connected_reddit_accounts",
                to="core.person",
            ),
        ),
        migrations.AlterField(
            model_name="connectedredditaccount",
            name="reddit_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connected_activitypub_accounts",
                to="core.redditaccount",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="connectedredditaccount",
            unique_together={("reddit_account", "actor")},
        ),
        migrations.AlterUniqueTogether(
            name="endorsement",
            unique_together={("endorser", "endorsed")},
        ),
        migrations.CreateModel(
            name="RedditToCommunityRecommendationEntry",
            fields=[
                (
                    "changefeedentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.changefeedentry",
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_entries",
                        to="core.reddittocommunityrecommendation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.changefeedentry",),
        ),
    ]
