# Generated by Django 4.2.6 on 2023-10-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_reddittolemmycommunity_automatic_comment_policy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="redditaccount",
            name="marked_as_bot",
            field=models.BooleanField(default=False),
        ),
    ]
