# Generated by Django 4.2.13 on 2024-07-19 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_fediversedinstance_portal_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="url",
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="person",
            name="url",
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="reddittocommunityrecommendationentry",
            name="community",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recommendation_feed_entries",
                to="core.community",
            ),
        ),
        migrations.AddField(
            model_name="reddittocommunityrecommendationentry",
            name="subreddit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recommendation_feed_entries",
                to="core.redditcommunity",
            ),
        ),
        migrations.CreateModel(
            name="SyncJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("run_on", models.DateTimeField(auto_now_add=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_jobs",
                        to="core.fediversedinstance",
                    ),
                ),
            ],
        ),
    ]
