# Generated by Django 4.2.13 on 2024-07-19 23:40

from django.db import migrations

from fediverser.apps.core.models.common import AP_SERVER_SOFTWARE


def populate_person_url(apps, schema_editor):
    Person = apps.get_model("core", "Person")

    for person in Person.objects.all():
        person.url = f"https://{person.instance.domain}/u/{person.name}"
        person.save()


def populate_community_url(apps, schema_editor):
    Community = apps.get_model("core", "Community")

    for c in Community.objects.all():
        c.url = {
            AP_SERVER_SOFTWARE.lemmy: f"https://{c.instance.domain}/c/{c.name}",
            AP_SERVER_SOFTWARE.kbin: f"https://{c.instance.domain}/m/{c.name}",
        }.get(c.instance.software)
        c.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_community_url_person_url_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_person_url, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(populate_community_url, reverse_code=migrations.RunPython.noop),
    ]
