# Generated by Django 4.2.6 on 2023-10-15 22:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_duplicated_lemmy_mirrored_posts"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lemmymirroredpost",
            unique_together={
                ("reddit_submission", "lemmy_post_id"),
                ("reddit_submission", "lemmy_community"),
            },
        ),
    ]
