# Generated by Django 4.2.13 on 2024-07-19 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_break_recommendation_changefeed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reddittocommunityrecommendationentry",
            name="recommendation",
        ),
        migrations.AlterField(
            model_name="reddittocommunityrecommendationentry",
            name="community",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendation_feed_entries",
                to="core.community",
            ),
        ),
        migrations.AlterField(
            model_name="reddittocommunityrecommendationentry",
            name="subreddit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendation_feed_entries",
                to="core.redditcommunity",
            ),
        ),
    ]
