# Generated by Django 4.2.13 on 2024-07-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_remove_reddittocommunityrecommendationentry_recommendation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="changefeedentry",
            options={"verbose_name_plural": "Change Entries"},
        ),
        migrations.AlterField(
            model_name="community",
            name="url",
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
