# Generated by Django 4.2.13 on 2024-07-20 21:06

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_changefeedentry_options_alter_community_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetInstanceCountry",
            fields=[
                (
                    "changerequest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.changerequest",
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="country_selection_requests",
                        to="core.instance",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.changerequest",),
        ),
        migrations.CreateModel(
            name="InstanceExtraInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("invite_only", models.BooleanField(blank=True, null=True)),
                ("application_required", models.BooleanField(blank=True, null=True)),
                ("payment_required", models.BooleanField(default=False)),
                (
                    "instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra",
                        to="core.instance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstanceCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_countries",
                        to="core.instance",
                    ),
                ),
            ],
            options={
                "unique_together": {("instance", "country")},
            },
        ),
    ]
