# Generated by Django 4.2.13 on 2024-07-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_setinstancecountry_instanceextrainformation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="tracked_subreddits",
            field=models.ManyToManyField(to="core.redditcommunity"),
        ),
    ]
