# Generated by Django 4.2.6 on 2023-10-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_redditaccount_controller"),
    ]

    operations = [
        migrations.AddField(
            model_name="redditcommunity",
            name="last_synced_at",
            field=models.DateTimeField(null=True),
        ),
    ]
