# Generated by Django 4.2.13 on 2024-07-22 15:56

import django.db.models.deletion
from django.db import migrations, models


def break_reddit_entries(apps, schema_editor):
    ConnectedRedditAccountEntry = apps.get_model("core", "ConnectedRedditAccountEntry")

    for entry in ConnectedRedditAccountEntry.objects.all():
        entry.reddit_account = entry.connection.reddit_account
        entry.actor = entry.connection.actor
        entry.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_useraccount_tracked_subreddits"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectedredditaccountentry",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reddit_connection_feed_entries",
                to="core.person",
            ),
        ),
        migrations.AddField(
            model_name="connectedredditaccountentry",
            name="reddit_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connection_feed_entries",
                to="core.redditaccount",
            ),
        ),
        migrations.RunPython(break_reddit_entries, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="connectedredditaccountentry",
            name="connection",
        ),
        migrations.AlterField(
            model_name="connectedredditaccountentry",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reddit_connection_feed_entries",
                to="core.person",
            ),
        ),
        migrations.AlterField(
            model_name="connectedredditaccountentry",
            name="reddit_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connection_feed_entries",
                to="core.redditaccount",
            ),
        ),
    ]
