# Generated by Django 4.2.6 on 2023-10-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_redditcommunity_last_synced_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="redditaccount",
            name="subreddits",
            field=models.ManyToManyField(to="core.redditcommunity", blank=True),
        ),
    ]
