# Generated by Django 4.2.6 on 2023-11-22 23:54

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_redditaccount_subreddits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redditcomment",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("retrieved", "retrieved"),
                    ("accepted", "accepted"),
                    ("rejected", "rejected"),
                    ("failed", "failed"),
                    ("mirrored", "mirrored"),
                ],
                default="retrieved",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="redditsubmission",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("retrieved", "retrieved"),
                    ("accepted", "accepted"),
                    ("rejected", "rejected"),
                    ("failed", "failed"),
                    ("mirrored", "mirrored"),
                ],
                default="retrieved",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
    ]
