# Generated by Django 4.2.13 on 2024-07-25 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_communityannotation_instanceannotation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="reddit_account",
        ),
    ]
