# Generated by Django 4.2.13 on 2024-07-29 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_remove_useraccount_reddit_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="feed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="core.feed"
            ),
        ),
        migrations.CreateModel(
            name="RedditApplicationKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("client_id", models.CharField(max_length=32)),
                ("client_secret", models.CharField(max_length=32)),
                ("password", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_keys",
                        to="core.redditaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RedditModerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderates",
                        to="core.redditaccount",
                    ),
                ),
                (
                    "subreddit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderators",
                        to="core.redditcommunity",
                    ),
                ),
            ],
            options={
                "unique_together": {("subreddit", "account")},
            },
        ),
    ]
