# Generated by Django 4.2.13 on 2024-07-29 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("socialaccount", "0006_alter_socialaccount_extra_data"),
        ("core", "0020_alter_entry_feed_redditapplicationkey_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="RedditAccountAuthorizedScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("creddits", "Spend reddit gold creddits"),
                            ("submit", "Submit Content"),
                            ("privatemessages", "Private Messages"),
                            ("report", "Report content"),
                            ("modnote", "Mod Note"),
                            ("modcontributors", "Approve and ban users"),
                            ("modmail", "New Modmail"),
                            ("modconfig", "Moderate Subreddit Configuration"),
                            ("modposts", "Moderate Posts"),
                            ("modflair", "Moderate Flair"),
                            ("modothers", "Invite or remove other moderators"),
                            ("modtraffic", "Subreddit Traffic"),
                            ("modwiki", "Moderate Wiki"),
                            (
                                "modself",
                                "Make changes to your subreddit moderator and contributor status",
                            ),
                            ("account", "Update account information"),
                            ("edit", "Edit Posts"),
                            ("subscribe", "Edit My Subscriptions"),
                            ("structuredstyles", "Edit structured styles"),
                            ("wikiedit", "Wiki Editing"),
                            ("read", "Read Content"),
                            ("wikiread", "Read Wiki Pages"),
                            ("mysubreddits", "My Subreddits"),
                            ("modlog", "Moderation Log"),
                            ("identity", "My Identity"),
                            ("history", "History"),
                            ("save", "Save Content"),
                            ("flair", "Manage My Flair"),
                            ("vote", "Vote"),
                            ("livemanage", "Manage live threads"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "social_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reddit_scopes",
                        to="socialaccount.socialaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RedditorInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("accepted", models.BooleanField(default=False, verbose_name="accepted")),
                ("key", models.CharField(max_length=64, unique=True, verbose_name="key")),
                ("sent", models.DateTimeField(null=True, verbose_name="sent")),
                (
                    "inviter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="inviter",
                    ),
                ),
                (
                    "redditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="core.redditaccount",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invites_sent",
                        to="core.invitetemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="communityinvitetemplate",
            name="id",
        ),
        migrations.RemoveField(
            model_name="communityinvitetemplate",
            name="message",
        ),
        migrations.DeleteModel(
            name="CommunityInvite",
        ),
        migrations.AddField(
            model_name="communityinvitetemplate",
            name="invitetemplate_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="core.invitetemplate",
            ),
            preserve_default=False,
        ),
    ]
