# Generated by Django 4.2.13 on 2024-07-31 09:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_invitetemplate_redditaccountauthorizedscope_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedditorDeclinedInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("supporter", "I fully support Reddit and their management"),
                            ("employee", "I work for Reddit"),
                            ("investor", "I am an investor in Reddit"),
                            ("already_migrated", "Helping with migration efforts on another site"),
                            (
                                "not_interested",
                                "Not interested in contributing to migration efforts",
                            ),
                            ("other", "Other"),
                        ],
                        default="supporter",
                        max_length=16,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Anything you like to share?", null=True
                    ),
                ),
                (
                    "redditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declined_invites",
                        to="core.redditaccount",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
