# Generated by Django 4.2.13 on 2024-08-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_redditordeclinedinvite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="software",
            field=models.CharField(
                choices=[
                    ("lemmy", "Lemmy"),
                    ("kbin", "Kbin"),
                    ("mbin", "Mbin"),
                    ("mastodon", "Mastodon"),
                    ("PieFed", "PieFed"),
                ],
                max_length=30,
            ),
        ),
    ]
