# Generated by Django 4.2.13 on 2024-08-23 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_alter_instance_software"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetInstanceAsClosed",
            fields=[
                (
                    "changerequest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.changerequest",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instance_closed_annotations",
                        to="core.instance",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.changerequest",),
        ),
        migrations.CreateModel(
            name="SetInstanceAsAbandoned",
            fields=[
                (
                    "changerequest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.changerequest",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instance_abandoned_annotations",
                        to="core.instance",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.changerequest",),
        ),
    ]
