from django.db.models import TextChoices
from model_utils import Choices


class AutomaticSubmissionPolicies(TextChoices):
    NONE = ("Disabled", "No automatic submission allowed")
    LINK_ONLY = ("Link Only", "Only external links")
    SELF_POST_ONLY = ("Self Only", "Only self-posts")
    FULL = ("Full", "All submissions")


class AutomaticCommentPolicies(TextChoices):
    NONE = ("Disabled", "Comment threads will not be mirrored")
    LINK_ONLY = ("Link Only", "Mirror comment threads for external links")
    SELF_POST_ONLY = ("Self Only", "Mirror comment threads for self-posts")
    FULL = ("Full", "Mirror all comment threads")


class Locales(TextChoices):
    AF_NA = "Afrikaans (Namibia)"
    AF_ZA = "Afrikaans (South Africa)"
    AF = "Afrikaans"
    AK_GH = "Akan (Ghana)"
    AK = "Akan"
    SQ_AL = "Albanian (Albania)"
    SQ = "Albanian"
    AM_ET = "Amharic (Ethiopia)"
    AM = "Amharic"
    AR_DZ = "Arabic (Algeria)"
    AR_BH = "Arabic (Bahrain)"
    AR_EG = "Arabic (Egypt)"
    AR_IQ = "Arabic (Iraq)"
    AR_JO = "Arabic (Jordan)"
    AR_KW = "Arabic (Kuwait)"
    AR_LB = "Arabic (Lebanon)"
    AR_LY = "Arabic (Libya)"
    AR_MA = "Arabic (Morocco)"
    AR_OM = "Arabic (Oman)"
    AR_QA = "Arabic (Qatar)"
    AR_SA = "Arabic (Saudi Arabia)"
    AR_SD = "Arabic (Sudan)"
    AR_SY = "Arabic (Syria)"
    AR_TN = "Arabic (Tunisia)"
    AR_AE = "Arabic (United Arab Emirates)"
    AR_YE = "Arabic (Yemen)"
    AR = "Arabic"
    HY_AM = "Armenian (Armenia)"
    HY = "Armenian"
    AS_IN = "Assamese (India)"
    AS = "Assamese"
    ASA_TZ = "Asu (Tanzania)"
    ASA = "Asu"
    AZ_CYRL = "Azerbaijani (Cyrillic)"
    AZ_CYRL_AZ = "Azerbaijani (Cyrillic, Azerbaijan)"
    AZ_LATN = "Azerbaijani (Latin)"
    AZ_LATN_AZ = "Azerbaijani (Latin, Azerbaijan)"
    AZ = "Azerbaijani"
    BM_ML = "Bambara (Mali)"
    BM = "Bambara"
    EU_ES = "Basque (Spain)"
    EU = "Basque"
    BE_BY = "Belarusian (Belarus)"
    BE = "Belarusian"
    BEM_ZM = "Bemba (Zambia)"
    BEM = "Bemba"
    BEZ_TZ = "Bena (Tanzania)"
    BEZ = "Bena"
    BN_BD = "Bengali (Bangladesh)"
    BN_IN = "Bengali (India)"
    BN = "Bengali"
    BS_BA = "Bosnian (Bosnia and Herzegovina)"
    BS = "Bosnian"
    BG_BG = "Bulgarian (Bulgaria)"
    BG = "Bulgarian"
    MY_MM = "Burmese (Myanmar [Burma])"
    MY = "Burmese"
    YUE_HANT_HK = "Cantonese (Traditional, Hong Kong SAR China)"
    CA_ES = "Catalan (Spain)"
    CA = "Catalan"
    TZM_LATN = "Central Morocco Tamazight (Latin)"
    TZM_LATN_MA = "Central Morocco Tamazight (Latin, Morocco)"
    TZM = "Central Morocco Tamazight"
    CHR_US = "Cherokee (United States)"
    CHR = "Cherokee"
    CGG_UG = "Chiga (Uganda)"
    CGG = "Chiga"
    ZH_HANS = "Chinese (Simplified Han)"
    ZH_HANS_CN = "Chinese (Simplified Han, China)"
    ZH_HANS_HK = "Chinese (Simplified Han, Hong Kong SAR China)"
    ZH_HANS_MO = "Chinese (Simplified Han, Macau SAR China)"
    ZH_HANS_SG = "Chinese (Simplified Han, Singapore)"
    ZH_HANT = "Chinese (Traditional Han)"
    ZH_HANT_HK = "Chinese (Traditional Han, Hong Kong SAR China)"
    ZH_HANT_MO = "Chinese (Traditional Han, Macau SAR China)"
    ZH_HANT_TW = "Chinese (Traditional Han, Taiwan)"
    ZH = "Chinese"
    KW_GB = "Cornish (United Kingdom)"
    KW = "Cornish"
    HR_HR = "Croatian (Croatia)"
    HR = "Croatian"
    CS_CZ = "Czech (Czech Republic)"
    CS = "Czech"
    DA_DK = "Danish (Denmark)"
    DA = "Danish"
    NL_BE = "Dutch (Belgium)"
    NL_NL = "Dutch (Netherlands)"
    NL = "Dutch"
    EBU_KE = "Embu (Kenya)"
    EBU = "Embu"
    EN_AS = "English (American Samoa)"
    EN_AU = "English (Australia)"
    EN_BE = "English (Belgium)"
    EN_BZ = "English (Belize)"
    EN_BW = "English (Botswana)"
    EN_CA = "English (Canada)"
    EN_GU = "English (Guam)"
    EN_HK = "English (Hong Kong SAR China)"
    EN_IN = "English (India)"
    EN_IE = "English (Ireland)"
    EN_IL = "English (Israel)"
    EN_JM = "English (Jamaica)"
    EN_MT = "English (Malta)"
    EN_MH = "English (Marshall Islands)"
    EN_MU = "English (Mauritius)"
    EN_NA = "English (Namibia)"
    EN_NZ = "English (New Zealand)"
    EN_MP = "English (Northern Mariana Islands)"
    EN_PK = "English (Pakistan)"
    EN_PH = "English (Philippines)"
    EN_SG = "English (Singapore)"
    EN_ZA = "English (South Africa)"
    EN_TT = "English (Trinidad and Tobago)"
    EN_UM = "English (U.S. Minor Outlying Islands)"
    EN_VI = "English (U.S. Virgin Islands)"
    EN_GB = "English (United Kingdom)"
    EN_US = "English (United States)"
    EN_ZW = "English (Zimbabwe)"
    EN = "English"
    EO = "Esperanto"
    ET_EE = "Estonian (Estonia)"
    ET = "Estonian"
    EE_GH = "Ewe (Ghana)"
    EE_TG = "Ewe (Togo)"
    EE = "Ewe"
    FO_FO = "Faroese (Faroe Islands)"
    FO = "Faroese"
    FIL_PH = "Filipino (Philippines)"
    FIL = "Filipino"
    FI_FI = "Finnish (Finland)"
    FI = "Finnish"
    FR_BE = "French (Belgium)"
    FR_BJ = "French (Benin)"
    FR_BF = "French (Burkina Faso)"
    FR_BI = "French (Burundi)"
    FR_CM = "French (Cameroon)"
    FR_CA = "French (Canada)"
    FR_CF = "French (Central African Republic)"
    FR_TD = "French (Chad)"
    FR_KM = "French (Comoros)"
    FR_CG = "French (Congo - Brazzaville)"
    FR_CD = "French (Congo - Kinshasa)"
    FR_CI = "French (Côte d’Ivoire)"
    FR_DJ = "French (Djibouti)"
    FR_GQ = "French (Equatorial Guinea)"
    FR_FR = "French (France)"
    FR_GA = "French (Gabon)"
    FR_GP = "French (Guadeloupe)"
    FR_GN = "French (Guinea)"
    FR_LU = "French (Luxembourg)"
    FR_MG = "French (Madagascar)"
    FR_ML = "French (Mali)"
    FR_MQ = "French (Martinique)"
    FR_MC = "French (Monaco)"
    FR_NE = "French (Niger)"
    FR_RW = "French (Rwanda)"
    FR_RE = "French (Réunion)"
    FR_BL = "French (Saint Barthélemy)"
    FR_MF = "French (Saint Martin)"
    FR_SN = "French (Senegal)"
    FR_CH = "French (Switzerland)"
    FR_TG = "French (Togo)"
    FR = "French"
    FF_SN = "Fulah (Senegal)"
    FF = "Fulah"
    GL_ES = "Galician (Spain)"
    GL = "Galician"
    LG_UG = "Ganda (Uganda)"
    LG = "Ganda"
    KA_GE = "Georgian (Georgia)"
    KA = "Georgian"
    DE_AT = "German (Austria)"
    DE_BE = "German (Belgium)"
    DE_DE = "German (Germany)"
    DE_LI = "German (Liechtenstein)"
    DE_LU = "German (Luxembourg)"
    DE_CH = "German (Switzerland)"
    DE = "German"
    EL_CY = "Greek (Cyprus)"
    EL_GR = "Greek (Greece)"
    EL = "Greek"
    GU_IN = "Gujarati (India)"
    GU = "Gujarati"
    GUZ_KE = "Gusii (Kenya)"
    GUZ = "Gusii"
    HA_LATN = "Hausa (Latin)"
    HA_LATN_GH = "Hausa (Latin, Ghana)"
    HA_LATN_NE = "Hausa (Latin, Niger)"
    HA_LATN_NG = "Hausa (Latin, Nigeria)"
    HA = "Hausa"
    HAW_US = "Hawaiian (United States)"
    HAW = "Hawaiian"
    HE_IL = "Hebrew (Israel)"
    HE = "Hebrew"
    HI_IN = "Hindi (India)"
    HI = "Hindi"
    HU_HU = "Hungarian (Hungary)"
    HU = "Hungarian"
    IS_IS = "Icelandic (Iceland)"
    IS = "Icelandic"
    IG_NG = "Igbo (Nigeria)"
    IG = "Igbo"
    ID_ID = "Indonesian (Indonesia)"
    ID = "Indonesian"
    GA_IE = "Irish (Ireland)"
    GA = "Irish"
    IT_IT = "Italian (Italy)"
    IT_CH = "Italian (Switzerland)"
    IT = "Italian"
    JA_JP = "Japanese (Japan)"
    JA = "Japanese"
    KEA_CV = "Kabuverdianu (Cape Verde)"
    KEA = "Kabuverdianu"
    KAB_DZ = "Kabyle (Algeria)"
    KAB = "Kabyle"
    KL_GL = "Kalaallisut (Greenland)"
    KL = "Kalaallisut"
    KLN_KE = "Kalenjin (Kenya)"
    KLN = "Kalenjin"
    KAM_KE = "Kamba (Kenya)"
    KAM = "Kamba"
    KN_IN = "Kannada (India)"
    KN = "Kannada"
    KK_CYRL = "Kazakh (Cyrillic)"
    KK_CYRL_KZ = "Kazakh (Cyrillic, Kazakhstan)"
    KK = "Kazakh"
    KM_KH = "Khmer (Cambodia)"
    KM = "Khmer"
    KI_KE = "Kikuyu (Kenya)"
    KI = "Kikuyu"
    RW_RW = "Kinyarwanda (Rwanda)"
    RW = "Kinyarwanda"
    KOK_IN = "Konkani (India)"
    KOK = "Konkani"
    KO_KR = "Korean (South Korea)"
    KO = "Korean"
    KHQ_ML = "Koyra Chiini (Mali)"
    KHQ = "Koyra Chiini"
    SES_ML = "Koyraboro Senni (Mali)"
    SES = "Koyraboro Senni"
    LAG_TZ = "Langi (Tanzania)"
    LAG = "Langi"
    LV_LV = "Latvian (Latvia)"
    LV = "Latvian"
    LT_LT = "Lithuanian (Lithuania)"
    LT = "Lithuanian"
    LUO_KE = "Luo (Kenya)"
    LUO = "Luo"
    LUY_KE = "Luyia (Kenya)"
    LUY = "Luyia"
    MK_MK = "Macedonian (Macedonia)"
    MK = "Macedonian"
    JMC_TZ = "Machame (Tanzania)"
    JMC = "Machame"
    KDE_TZ = "Makonde (Tanzania)"
    KDE = "Makonde"
    MG_MG = "Malagasy (Madagascar)"
    MG = "Malagasy"
    MS_BN = "Malay (Brunei)"
    MS_MY = "Malay (Malaysia)"
    MS = "Malay"
    ML_IN = "Malayalam (India)"
    ML = "Malayalam"
    MT_MT = "Maltese (Malta)"
    MT = "Maltese"
    GV_GB = "Manx (United Kingdom)"
    GV = "Manx"
    MR_IN = "Marathi (India)"
    MR = "Marathi"
    MAS_KE = "Masai (Kenya)"
    MAS_TZ = "Masai (Tanzania)"
    MAS = "Masai"
    MER_KE = "Meru (Kenya)"
    MER = "Meru"
    MFE_MU = "Morisyen (Mauritius)"
    MFE = "Morisyen"
    NAQ_NA = "Nama (Namibia)"
    NAQ = "Nama"
    NE_IN = "Nepali (India)"
    NE_NP = "Nepali (Nepal)"
    NE = "Nepali"
    ND_ZW = "North Ndebele (Zimbabwe)"
    ND = "North Ndebele"
    NB_NO = "Norwegian Bokmål (Norway)"
    NB = "Norwegian Bokmål"
    NN_NO = "Norwegian Nynorsk (Norway)"
    NN = "Norwegian Nynorsk"
    NYN_UG = "Nyankole (Uganda)"
    NYN = "Nyankole"
    OR_IN = "Oriya (India)"
    OR = "Oriya"
    OM_ET = "Oromo (Ethiopia)"
    OM_KE = "Oromo (Kenya)"
    OM = "Oromo"
    PS_AF = "Pashto (Afghanistan)"
    PS = "Pashto"
    FA_AF = "Persian (Afghanistan)"
    FA_IR = "Persian (Iran)"
    FA = "Persian"
    PL_PL = "Polish (Poland)"
    PL = "Polish"
    PT_BR = "Portuguese (Brazil)"
    PT_GW = "Portuguese (Guinea-Bissau)"
    PT_MZ = "Portuguese (Mozambique)"
    PT_PT = "Portuguese (Portugal)"
    PT = "Portuguese"
    PA_ARAB = "Punjabi (Arabic)"
    PA_ARAB_PK = "Punjabi (Arabic, Pakistan)"
    PA_GURU = "Punjabi (Gurmukhi)"
    PA_GURU_IN = "Punjabi (Gurmukhi, India)"
    PA = "Punjabi"
    RO_MD = "Romanian (Moldova)"
    RO_RO = "Romanian (Romania)"
    RO = "Romanian"
    RM_CH = "Romansh (Switzerland)"
    RM = "Romansh"
    ROF_TZ = "Rombo (Tanzania)"
    ROF = "Rombo"
    RU_MD = "Russian (Moldova)"
    RU_RU = "Russian (Russia)"
    RU_UA = "Russian (Ukraine)"
    RU = "Russian"
    RWK_TZ = "Rwa (Tanzania)"
    RWK = "Rwa"
    SAQ_KE = "Samburu (Kenya)"
    SAQ = "Samburu"
    SG_CF = "Sango (Central African Republic)"
    SG = "Sango"
    SEH_MZ = "Sena (Mozambique)"
    SEH = "Sena"
    SR_CYRL = "Serbian (Cyrillic)"
    SR_CYRL_BA = "Serbian (Cyrillic, Bosnia and Herzegovina)"
    SR_CYRL_ME = "Serbian (Cyrillic, Montenegro)"
    SR_CYRL_RS = "Serbian (Cyrillic, Serbia)"
    SR_LATN = "Serbian (Latin)"
    SR_LATN_BA = "Serbian (Latin, Bosnia and Herzegovina)"
    SR_LATN_ME = "Serbian (Latin, Montenegro)"
    SR_LATN_RS = "Serbian (Latin, Serbia)"
    SR = "Serbian"
    SN_ZW = "Shona (Zimbabwe)"
    SN = "Shona"
    II_CN = "Sichuan Yi (China)"
    II = "Sichuan Yi"
    SI_LK = "Sinhala (Sri Lanka)"
    SI = "Sinhala"
    SK_SK = "Slovak (Slovakia)"
    SK = "Slovak"
    SL_SI = "Slovenian (Slovenia)"
    SL = "Slovenian"
    XOG_UG = "Soga (Uganda)"
    XOG = "Soga"
    SO_DJ = "Somali (Djibouti)"
    SO_ET = "Somali (Ethiopia)"
    SO_KE = "Somali (Kenya)"
    SO_SO = "Somali (Somalia)"
    SO = "Somali"
    ES_AR = "Spanish (Argentina)"
    ES_BO = "Spanish (Bolivia)"
    ES_CL = "Spanish (Chile)"
    ES_CO = "Spanish (Colombia)"
    ES_CR = "Spanish (Costa Rica)"
    ES_DO = "Spanish (Dominican Republic)"
    ES_EC = "Spanish (Ecuador)"
    ES_SV = "Spanish (El Salvador)"
    ES_GQ = "Spanish (Equatorial Guinea)"
    ES_GT = "Spanish (Guatemala)"
    ES_HN = "Spanish (Honduras)"
    ES_419 = "Spanish (Latin America)"
    ES_MX = "Spanish (Mexico)"
    ES_NI = "Spanish (Nicaragua)"
    ES_PA = "Spanish (Panama)"
    ES_PY = "Spanish (Paraguay)"
    ES_PE = "Spanish (Peru)"
    ES_PR = "Spanish (Puerto Rico)"
    ES_ES = "Spanish (Spain)"
    ES_US = "Spanish (United States)"
    ES_UY = "Spanish (Uruguay)"
    ES_VE = "Spanish (Venezuela)"
    ES = "Spanish"
    SW_KE = "Swahili (Kenya)"
    SW_TZ = "Swahili (Tanzania)"
    SW = "Swahili"
    SV_FI = "Swedish (Finland)"
    SV_SE = "Swedish (Sweden)"
    SV = "Swedish"
    GSW_CH = "Swiss German (Switzerland)"
    GSW = "Swiss German"
    SHI_LATN = "Tachelhit (Latin)"
    SHI_LATN_MA = "Tachelhit (Latin, Morocco)"
    SHI_TFNG = "Tachelhit (Tifinagh)"
    SHI_TFNG_MA = "Tachelhit (Tifinagh, Morocco)"
    SHI = "Tachelhit"
    DAV_KE = "Taita (Kenya)"
    DAV = "Taita"
    TA_IN = "Tamil (India)"
    TA_LK = "Tamil (Sri Lanka)"
    TA = "Tamil"
    TE_IN = "Telugu (India)"
    TE = "Telugu"
    TEO_KE = "Teso (Kenya)"
    TEO_UG = "Teso (Uganda)"
    TEO = "Teso"
    TH_TH = "Thai (Thailand)"
    TH = "Thai"
    BO_CN = "Tibetan (China)"
    BO_IN = "Tibetan (India)"
    BO = "Tibetan"
    TI_ER = "Tigrinya (Eritrea)"
    TI_ET = "Tigrinya (Ethiopia)"
    TI = "Tigrinya"
    TO_TO = "Tonga (Tonga)"
    TO = "Tonga"
    TR_TR = "Turkish (Turkey)"
    TR = "Turkish"
    UK_UA = "Ukrainian (Ukraine)"
    UK = "Ukrainian"
    UR_IN = "Urdu (India)"
    UR_PK = "Urdu (Pakistan)"
    UR = "Urdu"
    UZ_ARAB = "Uzbek (Arabic)"
    UZ_ARAB_AF = "Uzbek (Arabic, Afghanistan)"
    UZ_CYRL = "Uzbek (Cyrillic)"
    UZ_CYRL_UZ = "Uzbek (Cyrillic, Uzbekistan)"
    UZ_LATN = "Uzbek (Latin)"
    UZ_LATN_UZ = "Uzbek (Latin, Uzbekistan)"
    UZ = "Uzbek"
    VI_VN = "Vietnamese (Vietnam)"
    VI = "Vietnamese"
    VUN_TZ = "Vunjo (Tanzania)"
    VUN = "Vunjo"
    CY_GB = "Welsh (United Kingdom)"
    CY = "Welsh"
    YO_NG = "Yoruba (Nigeria)"
    YO = "Yoruba"
    ZU_ZA = "Zulu (South Africa)"
    ZU = "Zulu"


class LanguageCodes(TextChoices):
    AF = ("Afrikaans", "Afrikaans")
    AM = ("Amharic", "አማርኛ")
    AR = ("Arabic", "العربية")
    ARN = ("Mapudungun", "Mapudungun")
    ARY = ("Moroccan Arabic", "الدارجة المغربية")
    AS = ("Assamese", "অসমীয়া")
    AZ = ("Azerbaijani", "Azərbaycan")
    BA = ("Bashkir", "Башҡорт")
    BE = ("Belarusian", "беларуская")
    BG = ("Bulgarian", "български")
    BN = ("Bengali", "বাংলা")
    BO = ("Tibetan", "བོད་ཡིག")
    BR = ("Breton", "brezhoneg")
    BS = ("Bosnian", "bosanski/босански")
    CA = ("Catalan", "català")
    CO = ("Corsican", "Corsu")
    CS = ("Czech", "čeština")
    CY = ("Welsh", "Cymraeg")
    DA = ("Danish", "dansk")
    DE = ("German", "Deutsch")
    DSB = ("Lower Sorbian", "dolnoserbšćina")
    DV = ("Divehi", "ދިވެހިބަސް")
    EL = ("Greek", "Ελληνικά")
    EN = ("English", "English")
    ES = ("Spanish", "español")
    ET = ("Estonian", "eesti")
    EU = ("Basque", "euskara")
    FA = ("Persian", "فارسى")
    FI = ("Finnish", "suomi")
    FIL = ("Filipino", "Filipino")
    FO = ("Faroese", "føroyskt")
    FR = ("French", "français")
    FY = ("Frisian", "Frysk")
    GA = ("Irish", "Gaeilge")
    GD = ("Scottish Gaelic", "Gàidhlig")
    GL = ("Galician", "galego")
    GSW = ("Swiss German", "Schweizerdeutsch")
    GU = ("Gujarati", "ગુજરાતી")
    HA = ("Hausa", "Hausa")
    HE = ("Hebrew", "עברית")
    HI = ("Hindi", "हिंदी")
    HR = ("Croatian", "hrvatski")
    HRV = ("Serbo-Croatian", "srpskohrvatski/српскохрватски")
    HSB = ("Upper Sorbian", "hornjoserbšćina")
    HU = ("Hungarian", "magyar")
    HY = ("Armenian", "Հայերեն")
    ID = ("Indonesian", "Bahasa Indonesia")
    IG = ("Igbo", "Igbo")
    II = ("Yi", "ꆈꌠꁱꂷ")
    IS = ("Icelandic", "íslenska")
    IT = ("Italian", "italiano")
    IU = ("Inuktitut", "Inuktitut /ᐃᓄᒃᑎᑐᑦ (ᑲᓇᑕ)")
    JA = ("Japanese", "日本語")
    KA = ("Georgian", "ქართული")
    KK = ("Kazakh", "Қазақша")
    KL = ("Greenlandic", "kalaallisut")
    KM = ("Khmer", "ខ្មែរ")
    KN = ("Kannada", "ಕನ್ನಡ")
    KO = ("Korean", "한국어")
    KOK = ("Konkani", "कोंकणी")
    KB = ("Kurdi", "کوردی/Kurdî")
    KY = ("Kyrgyz", "Кыргыз")
    LB = ("Luxembourgish", "Lëtzebuergesch")
    LO = ("Lao", "ລາວ")
    LT = ("Lithuanian", "lietuvių")
    LV = ("Latvian", "latviešu")
    MI = ("Maori", "Reo Māori")
    MK = ("Macedonian", "македонски јазик")
    ML = ("Malayalam", "മലയാളം")
    MN = ("Mongolian", "Монгол хэл/ᠮᠤᠨᠭᠭᠤᠯ ᠬᠡᠯᠡ")
    MOH = ("Mohawk", "Kanien kéha")
    MR = ("Marathi", "मराठी")
    MS = ("Malay", "Bahasa Malaysia")
    MT = ("Maltese", "Malti")
    MY = ("Burmese", "မြန်မာဘာသာ")
    NB = ("Norwegian (Bokmål", "norsk (bokmål)")
    NE = ("Nepali", "नेपाली (नेपाल)")
    NL = ("Dutch", "Nederlands")
    NN = ("Norwegian (Nynorsk", "norsk (nynorsk)")
    NO = ("Norwegian", "norsk")
    OC = ("Occitan", "occitan")
    OR = ("Odia", "ଓଡ଼ିଆ")
    PAP = ("Papiamento", "Papiamentu")
    PA = ("Punjabi", "ਪੰਜਾਬੀ / پنجابی")
    PL = ("Polish", "polski")
    PRS = ("Dari", "درى")
    PS = ("Pashto", "پښتو")
    PT = ("Portuguese", "português")
    QUC = ("K'iche", "K'iche")
    QU = ("Quechua", "runasimi")
    RM = ("Romansh", "Rumantsch")
    RO = ("Romanian", "română")
    RU = ("Russian", "русский")
    RW = ("Kinyarwanda", "Kinyarwanda")
    SA = ("Sanskrit", "संस्कृत")
    SAH = ("Yakut", "саха")
    SE = ("Sami (Northern", "davvisámegiella")
    SI = ("Sinhala", "සිංහල")
    SK = ("Slovak", "slovenčina")
    SL = ("Slovenian", "slovenski")
    SMA = ("Sami (Southern", "åarjelsaemiengiele")
    SMJ = ("Sami (Lule", "julevusámegiella")
    SMN = ("Sami (Inari", "sämikielâ")
    SMS = ("Sami (Skolt", "sääʹmǩiõll")
    SQ = ("Albanian", "shqip")
    SR = ("Serbian", "srpski/српски")
    ST = ("Sesotho", "Sesotho sa Leboa")
    SV = ("Swedish", "svenska")
    SW = ("Kiswahili", "Kiswahili")
    SYC = ("Syriac", "ܣܘܪܝܝܐ")
    TA = ("Tamil", "தமிழ்")
    TE = ("Telugu", "తెలుగు")
    TG = ("Tajik", "Тоҷикӣ")
    TH = ("Thai", "ไทย")
    TK = ("Turkmen", "türkmençe")
    TN = ("Tswana", "Setswana")
    TR = ("Turkish", "Türkçe")
    TT = ("Tatar", "Татарча")
    TZM = ("Tamazight", "Tamazight")
    UG = ("Uyghur", "ئۇيغۇرچە")
    UK = ("Ukrainian", "українська")
    UR = ("Urdu", "اُردو")
    UZ = ("Uzbek", "Uzbek/Ўзбек")
    VI = ("Vietnamese", "Tiếng Việt")
    WO = ("Wolof", "Wolof")
    XH = ("Xhosa", "isiXhosa")
    YO = ("Yoruba", "Yoruba")
    ZH = ("Chinese", "中文")
    ZU = ("Zulu", "isiZulu")


SOURCE_CONTENT_STATUSES = Choices("retrieved", "accepted", "rejected", "failed", "mirrored")
